### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by GeorgeKirm** [MusicGenerator/mumble-ruby-pluginbot-docs#1]
Problem:
In documentation, inside of the file "appliance.rst", under "Download the appliance" the following link "https://www.natenom.com/fixme/" gives 404

Expected:
Go to the right subdirectory, which contains the right file to download

How to reproduce:
Click the link under "Download the appliance", then it will redirect you to the "www.natenom.com" site but it will not find the subdirectory

**Comment by dafoxia** [comment]
This project is at heavy work at the moment.
A new version should be released soon. (hours to days)
The docs are almost complete, the bot is under test. An apliance for download does not exist at the moment, but is in work.
It will be fixed soon. :)

**Comment by GeorgeKirm** [comment]
I found a link of an old version of apliance in the history of that file, it works very good for me. Thanks for the work!

**Comment by Natenom** [comment]
The documentation is now updated. You should try the new version :)

BTW: There are now two appliances, one with terminal only and one with a Pseudo GUI on a Desktop...
